apiVersion: "serving.kserve.io/v1alpha2"
kind: "InferenceService"
metadata:
  name: "style-sample"
spec:
  default:
    predictor:
      onnx:
        storageUri: "gs://kfserving-examples/onnx/style"
